var mongoose = require('mongoose');

//Schema Setup

var eventSchema = new mongoose.Schema({
	_id: mongoose.Schema.Types.ObjectId,
	eventName: {type: String},
	details: {type: String},
	location: {type: String},
	featured: {type: Boolean},
	image: {type: String},
	approve: {type: Boolean},
	address: {type: String},
	city: {type: String},
	state: {type: String},
	zipCode: {type: Number},
	displayContactName: {type: String},
	displayContactPhone: {type: String},
	eventDate: {type: Date},
	startDate: {type: Date},
	endDate: {type: Date},
	startTime: {type: String},
	endTime: {type: String},
	cost: {type: String},
	sponsor: {type: String},
	website: {type: String},
	tickets: {type: String},
	tags: {
		fineDining: Boolean,
		banquetHall: Boolean,
		asian: Boolean,
		fundraiser: Boolean,
		disco: Boolean,
		casual: Boolean,
		restaurant: Boolean,
		french: Boolean,
		dancing: Boolean,
		jazz: Boolean,
		buffet: Boolean,
		american: Boolean,
		seafoood: Boolean,
		festival: Boolean,
		ratPack: Boolean,
		brunch: Boolean,
		italian: Boolean,
		vegan: Boolean,
		liveEntertainment: Boolean,
		motown: Boolean,
		bar: Boolean,
		mediterranean: Boolean,
		vegetarian: Boolean,
		rock: Boolean,
		freestyle: Boolean,
		nightClub: Boolean,
		cuban: Boolean,
		glutenFree: Boolean,
		top40: Boolean,
		hiphopRB: Boolean,
		byob: Boolean,
		twentyOne: Boolean,
		eighteen: Boolean,
		family: Boolean,
		pet: Boolean,
		freeAdmission: Boolean
	},
	contactName: {type: String},
	contactPhone: {type: String},
	contactEmail: {type: String}
});

module.exports = mongoose.model('Event', eventSchema);
