var mongoose = require('mongoose');

//Schema Setup

var eventSchema = new mongoose.Schema({
	_id: mongoose.Schema.Types.ObjectId,
	eventName: {type: String},
	details: {type: String},
	location: {type: String},
	featured: {type: Boolean},
	image: {type: String},
	path: {type: String},
	approve: {type: Boolean},
	address: {type: String},
	city: {type: String},
	state: {type: String},
	zipCode: {type: Number},
	displayContactName: {type: String},
	displayContactPhone: {type: String},
	displayContactEmail: {type: String},
	eventDate: {type: Date},
	startDate: {type: Date},
	endDate: {type: Date},
	startTime: {type: String},
	endTime: {type: String},
	cost: {type: String},
	sponsor: {type: String},
	website: {type: String},
	tickets: {type: String},
	tags: {
		fineDining: String,
		banquetHall: String,
		asian: String,
		disco: String,
		casual: String,
		french: String,
		jazz: String,
		buffet: String,
		american: String,
		seafoood: String,
		ratPack: String,
		italian: String,
		vegan: String,
		liveEntertainment: String,
		motown: String,
		bar: String,
		mediterranean: String,
		vegetarian: String,
		rock: String,
		freestyle: String,
		nightClub: String,
		cuban: String,
		glutenFree: String,
		top40: String,
		hiphopRB: String,
		byob: String,
		pet: String,
		freeAdmission: String
	},
	audience: {type: String},
	eventType: {type: String},
	contactName: {type: String},
	contactPhone: {type: String},
	contactEmail: {type: String}
});

module.exports = mongoose.model('Event', eventSchema);
